"use client";
import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
import Image from "next/image";
import React from "react";
import { easeIn, motion } from "framer-motion";
const data = [
  {
    title: "Data Collection",
    description:
      "We only collect data that is necessary for the operation and improvement of our services. This includes data provided by the user and data automatically generated by the use of our application.",
  },
  {
    title: "Data Processing",
    description:
      "All data is processed in compliance with relevant data protection regulations. We ensure that data is processed fairly, transparently, and only for the purposes for which it was collected.",
  },
  {
    title: "Data Storage",
    description:
      "Customer data is securely stored using advanced encryption and security protocols. We take measures to protect data against unauthorized access, alteration, and destruction.",
  },
  {
    title: "Data Usage",
    description:
      "Customer data is used solely for the purpose of delivering and improving our services. We do not sell or share customer data with third parties without explicit consent, except as required by law.",
  },
  {
    title: "Data Sharing",
    description:
      "If data sharing is necessary for the provision of our services, we ensure that third parties comply with our stringent data protection standards.",
  },
  {
    title: "Data Disposal",
    description:
      "Customer data is retained only for as long as necessary to fulfill the purposes for which it was collected. Once data is no longer needed, it is securely disposed of in accordance with our data retention policies.",
  },
  {
    title: "User Rights",
    description:
      "We respect the rights of our users to access, correct, delete, or restrict the processing of their data. Users can exercise these rights by contacting us directly.",
  },
  {
    title: "Continuous Improvement",
    description:
      "We regularly review and update our data protection practices to ensure ongoing compliance with data protection regulations and to incorporate the latest security technologies.",
  },
];
const page = () => {
  const FADE_UP_ANIMATION_VARIANTS = {
    hidden: { opacity: 0, y: 10 },
    show: { opacity: 1, y: 0, transition: { type: "spring" } },
  };

  return (
    <div>
      <div className="bg-[#eff1fe]">
        <Navbar />
        <div className="bg-[#eff1fe] px-8 py-16  pb-28 text-[#383c4f] font-bold text-4xl">
          <div className="max-w-7xl mx-auto lg:px-20 px-8">
            Data and Privacy Policy
          </div>{" "}
        </div>
      </div>
      <div className="max-w-7xl mx-auto ">
        <div className="flex flex-row flex-wrap gap-5">
          <div className="flex flex-col gap-5">
            <div className="w-full flex lg:flex-row flex-col items-center justify-center gap-5 my-10">
              <motion.div
                initial="hidden"
                animate="show"
                viewport={{ once: true }}
                variants={{
                  hidden: {},
                  show: {
                    transition: {
                      staggerChildren: 0.15,
                    },
                  },
                }}
                className="flex flex-col gap-1.5 font-bold text-xl items-start justify-center lg:w-1/2"
              >
                <motion.h2
                  variants={FADE_UP_ANIMATION_VARIANTS}
                  className="font-extrabold text-left text-4xl my-7 text-tp "
                >
                  Data and Privacy Policy
                </motion.h2>
                <motion.p
                  variants={FADE_UP_ANIMATION_VARIANTS}
                  className="text-base text-[#5c6885]"
                >
                  At Seller Circle - AJ Digi Media Pvt Ltd, protecting customer
                  data and ensuring data privacy are of paramount importance. We
                  employ various privacy-enhancing technologies and implement
                  comprehensive data handling policies to safeguard customer
                  data throughout the entire lifecycle of our systems and
                  services. Our data handling policies include:
                </motion.p>
              </motion.div>
              <motion.div
                className=""
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                transition={{ delay: 0.5, transition: easeIn }}
              >
                <Image src="/images/17.png" alt="" width={600} height={600} />
              </motion.div>
            </div>
          </div>
          <div className="flex flex-row flex-wrap gap-5 mb-20 pb-20">
            {data.map((item, idx) => (
              <motion.div
                initial={{ opacity: 0, y: 0 }}
                animate={{ opacity: 1, y: 100 }}
                transition={{
                  delay: 0.2 * idx,
                  transition: easeIn,
                  type: "spring",
                }}
                className="bg-white  p-10 shadow-lg min-w-[280px] max-w-[400px] flex flex-col gap-5"
                key={idx}
              >
                <h2 className="text-3xl font-bold text-[#303e5b]">
                  {item.title}
                </h2>
                <p className="text-[#525e80]">{item.description}</p>
              </motion.div>
            ))}
          </div>
        </div>
      </div>
      <Footer />
    </div>
  );
};

export default page;
